### ISSUE TITLE
It's a cool job! Would you like to share the BBP dataset?  

### ISSUE THREAD

**Issue by big-rain** [marissaweis/ssl_neuron#2]
In both https://microcircuits.epfl.ch/#/main and paper, "Reconstruction and Simulation of Neocortical Microcircuitry", I couldn't even find the class information of the neuron morphology (15 classes). Could you please provide the expert annotations for the BBP dataset. My email address is [p23101002@stu.ahu.edu.cn](mailto:p23101002@stu.ahu.edu.cn) . Thank you very much!!!

**Comment by marissaweis** [comment]
Thank you for the interest in our work! I wrote you an e-mail.
